### ISSUE TITLE
can you make support 2020?

### ISSUE THREAD

**Issue by zero16832** [spacehamster/UtinyRipperExporter#5]
can you make support 2020?

**Comment by spacehamster** [comment]
What is the issue with 2020?

**Comment by zero16832** [comment]
can't load the game make with unity 2020

**Comment by spacehamster** [comment]
Thats not enough to go on.
Can you post the errors you are receiving and what games you are targeting?
Also any other relevant details would help.

**Comment by zero16832** [comment]
here is the game's link.
[https://drive.google.com/file/d/1BBvlsyKv84h-2KI2OzpNAbfaduFxB9Re/view?usp=sharing](url)
when i try to unpack the game,it can't open it.

**Comment by spacehamster** [comment]
uTinyRipper throws `System.Exception: 'Some data left'` while decoding the LZ4 stream in data.unity3d. I'm not sure if the file is corrupted or it is just using a version of LZ4 that uTinyRipper does not recognize. 

I also created a simple test 2020 unity project and uTinyRipper does not pick up all the files in the project and does not recognize it as a valid project.

Fixing either of those issues is out of scope for this project and I suggest opening an issue with [uTinyRipper](https://github.com/mafaca/UtinyRipper)
